settings:
  proxy: ""
  batch_size: 20
  headless: true

stars:
  - { name: "高橋ほなみ", id: "121h" }
  - { name: "葵いぶき", id: "wbu" }
  - { name: "堀田真央", id: "12dr" }
  - { name: "青山七海", id: "12tl" }
  - { name: "椎名心春", id: "125p" }
  - { name: "三木環奈", id: "131f" }
  - { name: "八木奈々", id: "vjs" }
  - { name: "小坂七香", id: "11xv" }
  - { name: "一ノ瀬あおい", id: "12gg" }
  - { name: "宮崎千尋", id: "128q" }
  - { name: "百田光希", id: "11lb" }
  - { name: "白桃はな", id: "wlb" }
  - { name: "石川澪", id: "xvn" }
  - { name: "森歩乃花", id: "11ww" }
  - { name: "白上咲花", id: "127e" }
  - { name: "依本しおり", id: "12yi" }
  - { name: "乃坂ひより", id: "12mr" }
  - { name: "夏空りか", id: "12w7" }
  - { name: "miru", id: "xf2" }
  - { name: "新ありな", id: "zk9" }
  - { name: "楪カレン", id: "x2w" }
  - { name: "早坂ひめ", id: "11tj" }
  - { name: "野宮あん", id: "12vd" }
  - { name: "浜辺やよい", id: "13ir" }
  - { name: "望乃るい", id: "13mv" }
  - { name: "未歩なな", id: "z77" }
  - { name: "役野満里奈", id: "129i" }
  - { name: "安達夕莉", id: "zcc" }
  - { name: "三葉ちはる", id: "1011" }
  - { name: "絵恋空", id: "12mw" }
  - { name: "まなみ静奈", id: "11ie" }
  - { name: "小泉なぎさ", id: "13dg" }
  - { name: "涼森れむ", id: "uly" }
  - { name: "優木とあ", id: "12f9" }
  - { name: "楓ふうあ", id: "xog" }
  - { name: "和香なつき", id: "13c1" }
  - { name: "八掛うみ", id: "ws2" }
  - { name: "浅野こころ", id: "119g" }
  - { name: "清原みゆう", id: "10uf" }
  - { name: "柏木こなつ", id: "yz6" }
  - { name: "佐々木さき", id: "11gt" }
  - { name: "皆瀬あかり", id: "z2d" }
  - { name: "九野ひなの", id: "ziu" }
  - { name: "高瀬りな", id: "wti" }
  - { name: "皆月ひかる", id: "swx" }
  - { name: "新川空", id: "13wp" }
  - { name: "三佳詩", id: "1474" }
  - { name: "天神羽衣", id: "13jb" }
  - { name: "井上もも", id: "14d8" }
  - { name: "純白彩永", id: "13tf" }
  - { name: "白雪ひなの", id: "131a" }
  - { name: "三好佑香", id: "13nd" }
  - { name: "初美なのか", id: "1411" }
  - { name: "村上悠華", id: "115e" }
  - { name: "紫堂るい", id: "13pu" }
  - { name: "香水じゅん", id: "xiu" }
  - { name: "宇野みれい", id: "110h" }
  - { name: "山下紗和", id: "12xc" }
  - { name: "中森ななみ", id: "138l" }
  - { name: "姫森あむ", id: "14ir" }
  - { name: "渚恋生", id: "11df" }
  - { name: "桜ゆの", id: "1380" }
  - { name: "似鳥日菜", id: "zjx" }
  - { name: "福田ゆあ", id: "1498" }